### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by B1ack3ye** [BoltzmannEntropy/xtts2-ui#17]
When I try to start the app I get an error:

```
(venv) PS D:\Projekte\xtts2-ui> python .\app.py
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
Traceback (most recent call last):
  File "D:\Projekte\xtts2-ui\app.py", line 38, in <module>
    tts = TTS(model_name=params["model_name"]).to(device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\api.py", line 74, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\api.py", line 177, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
                       ^^^^^^^^^^^^
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\utils\synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\utils\synthesizer.py", line 161, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\config\__init__.py", line 97, in load_config
    config_class = register_config(model_name.lower())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\config\__init__.py", line 40, in register_config
    from TTS.tts.configs.xtts_config import XttsConfig
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\tts\configs\xtts_config.py", line 5, in <module>
    from TTS.tts.models.xtts import XttsArgs, XttsAudioConfig
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\tts\models\xtts.py", line 12, in <module>
    from TTS.tts.layers.xtts.stream_generator import init_stream_support
  File "D:\Projekte\xtts2-ui\venv\Lib\site-packages\TTS\tts\layers\xtts\stream_generator.py", line 24, in <module>
    from transformers.generation.utils import GenerateOutput, SampleOutput, logger
ImportError: cannot import name 'SampleOutput' from 'transformers.generation.utils' (D:\Projekte\xtts2-ui\venv\Lib\site-packages\transformers\generation\utils.py)
```

OS: Windows

**Comment by Anmol2059** [comment]
pip install transformers==4.33.0 should fix your issue

**Comment by B1ack3ye** [comment]
Worked.
