### ISSUE TITLE
error new install (maybe 6 month ago it works)

### ISSUE THREAD

**Issue by kalle07** [BoltzmannEntropy/xtts2-ui#38]
(i deleted all that runs fine)

Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\kallemst>d:

D:\>cd d:\xtts2-ui-boltzmann\

d:\xtts2-ui-boltzmann>git clone https://github.com/pbanuru/xtts2-ui.git
Cloning into 'xtts2-ui'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 120 (delta 25), reused 23 (delta 23), pack-reused 82 (from 1)
Receiving objects: 100% (120/120), 5.10 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (48/48), done.

d:\xtts2-ui-boltzmann>cd xtts2-ui

d:\xtts2-ui-boltzmann\xtts2-ui>python -m venv venv

d:\xtts2-ui-boltzmann\xtts2-ui>venv\Scripts\activate

(venv) d:\xtts2-ui-boltzmann\xtts2-ui>pip install torch torchvision torchaudio --index-url 
...
-> ALL FINE

(venv) d:\xtts2-ui-boltzmann\xtts2-ui>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting gradio==4.7.1
  Downloading gradio-4.7.1-py3-none-any.whl (16.5 MB)
     ---------------------------------------- 16.5/16.5 MB 6.9 MB/s eta 0:00:00
Collecting TTS==0.21.*
  Downloading TTS-0.21.3.tar.gz (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 7.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

ALL FINE!

INFO: pip is looking at multiple versions of sudachidict-core to determine which version is compatible with other requirements. This could take a while.
Collecting sudachidict-core>=20211220
  Downloading SudachiDict_core-20240716-py3-none-any.whl (72.0 MB)
     ---------------------------------------- 72.0/72.0 MB 7.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of anyio to determine which version is compatible with other requirements. This could take a while.
Collecting anyio
  Downloading anyio-4.6.2.post1-py3-none-any.whl (90 kB)

---SOME MORE---

INFO: pip is looking at multiple versions of aiohappyeyeballs to determine which version is compatible with other requirements. This could take a while.
  Downloading jieba-0.41.tar.gz (19.2 MB)
     ---------------------------------------- 19.2/19.2 MB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of jamo to determine which version is compatible with other requirements. This could take a while.
Collecting jamo
  Downloading jamo-0.4.0.tar.gz (7.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kallemst\AppData\Local\Temp\pip-install-4jeb0zfc\jamo_c00293110ab24aa282ddf8b964ec3b21\setup.py", line 11, in <module>
          long_description = f.read()
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 707: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) d:\xtts2-ui-boltzmann\xtts2-ui>pip install --upgrade TTS
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting TTS

--Some MORE ---

INFO: pip is looking at multiple versions of jamo to determine which version is compatible with other requirements. This could take a while.
Collecting jamo
  Downloading jamo-0.4.0.tar.gz (7.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kallemst\AppData\Local\Temp\pip-install-0y11hsat\jamo_8fcc85c1967a4ea38875379543419747\setup.py", line 11, in <module>
          long_description = f.read()
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 707: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) d:\xtts2-ui-boltzmann\xtts2-ui>python app.py
Traceback (most recent call last):
  File "d:\xtts2-ui-boltzmann\xtts2-ui\app.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

(venv) d:\xtts2-ui-boltzmann\xtts2-ui>

**Comment by Sun1ive** [comment]
same here

**Comment by BoltzmannEntropy** [comment]
Please try: set PYTHONUTF8=1 
I do not have a windows machine.

**Comment by kalle07** [comment]
i see ...
but YEAAAA we are windows-dummy users, where i should set that   : D
